/* global RETRIEVER_COLLECTION_NAME, BOOKING_COLLECTION_NAME, CONFIRMATION_COLLECTION_NAME */
const config = {
  RETRIEVER_COLLECTION_NAME: RETRIEVER_COLLECTION_NAME,
  BOOKING_COLLECTION_NAME: BOOKING_COLLECTION_NAME,
  CONFIRMATION_COLLECTION_NAME: CONFIRMATION_COLLECTION_NAME
};
export default config;
